name: Npm-Release

on:
    push:
      branches:
          - main

jobs:
    publish:
        runs-on: ubuntu-latest
        environment: github-pages
        steps:
            - uses: actions/checkout@v4
            - uses: DeLaGuardo/setup-clojure@12.5
              with:
                cli: "1.11.1.1139"
            - uses: actions/setup-node@v3
              with:
                node-version: "20"
            - name: npm release
              run: |
                npm ci && \
                npm run release
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: 'public/'
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
